version: 1.0.{build}
os: Visual Studio 2015
skip_tags: true
configuration: Release

before_build:
  - ps: .\scripts\set-version.ps1
  - cmd: dotnet --info
  - cmd: dotnet restore
  - choco install opencover.portable
  - choco install codecov
  - choco install xunit

build_script:
  - cmd: dotnet build -c Release

test_script:
  #- cmd: dotnet test -c release DeveLibVipsNuget.Tests\DeveLibVipsNuget.Tests.csproj
  - OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"test .\DeveLibVipsNuget.Tests\DeveLibVipsNuget.Tests.csproj -c Release" -oldstyle -output:.\DeveLibVipsNuget.Coverage.xml -filter:"+[DeveLibVipsNuget*]*"
  - codecov -f "DeveLibVipsNuget.Coverage.xml"
  
after_test:
  - cmd: dotnet pack -c Release DeveLibVipsNuget\
  - cmd: Scripts\GoRepack.cmd

artifacts:
- path: Scripts\DeveLibVipsNuget.7z
  name: droppackage7z
- path: Scripts\DeveLibVipsNuget.zip
  name: droppackagezip
- path: 'DeveLibVipsNuget\bin\Release\*.nupkg'
  name: nugetPackages

deploy:
- provider: GitHub
  auth_token:
    secure: do7S++r1rE5E3IZujCoMONsWYJNF7eoRoPyJbxSD851I850OlEq0gsHH/Tji7o00
  artifact: droppackage7z,droppackagezip,nugetPackages
- provider: NuGet
  api_key:
    secure: pVOzQthQbu7P9SUQwjG43ZEMcwAp7dVbe4BkDVEwJFu1gWK+L11L9mdfGLC5iO5Z
  skip_symbols: true
  artifact: /.*\.nupkg/